node {
    try {
        stage("Issue Here"){
            stage = "Issue Here"
            sh "exit 1"
        }

        stage("Never Run"){
            stage = "Never Run"
            echo "never run"
        }
    } catch (Exception | hudson.AbortException err) {
        print("Failed on stage: ${stage}")
        if(err.class == hudson.AbortException) {
            println("ABORTED!!!! ${err}")
        } else {println("SGW!!! ${err.getProperties()}")}
        throw err
    } finally {
        stage("Always Run"){
            print("Always Run")
        }
    }
}
