node {
    try {
        stage("Issue Here"){
            stage = "Issue Here"
            sh "exit 1"
        }

        stage("Never Run"){
            stage = "Never Run"
            echo "never run"
        }
        // currentBuild.result = 'SUCCESS'
    } catch (Exception err) {
        // currentBuild.result = 'FAILURE'
        print("Failed on stage: ${stage}")
        throw err
    } finally {
        stage("Always Run"){
            print("Always Run")
        }
    }
}
