node() {
    withCredentials([
        string(credentialsId: 'awssecrets', variable: 'aws_access_key_id'),
        string(credentialsId: 'awssecrets', variable: 'aws_secret_access_key'),
    ]) {

    }
}